language: node_js
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install -g gulp
    - npm install -g istanbul
    - npm install -g codeclimate-test-reporter
    - npm install
node_js:
  - "iojs-v2.3.4"
script:
    - gulp
    # '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && gulp upload-docs || true'
